version: '3.7'

services:
  postgresql:
    image: postgres:latest
    container_name: ${PROJECT_NAME?Variable not set}-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: mantap2Jozz!
    ports:
      - "5432:5432"
    networks:
      - app-network

  # apps:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: ${PROJECT_NAME?Variable not set}
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./src:/app/src
  #     - ./public:/app/public
  #   restart: unless-stopped
  #   ports:
  #     - 3092:3092
  #   networks:
  #     - app-network

# networks:
#   app-network:
#     driver: bridge
