version: '3.7'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: assessment
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: mantap2Jozz!
    ports:
      - "5432:5432"

  apps:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${PROJECT_NAME?Variable not set}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    ports:
      - 3092:3092
    command: sh -c "npm run migrate && npm run seed && npm start"

# networks:
#   default:
#     name: ${PROJECT_NETWORK?Variable not set}
